version: '2'
services:
  postgres:
    image: quay.io/azavea/postgis:postgres9.5-postgis2.2
    env_file: .env
    ports:
      - "5432:5432"

  nginx:
    image: rf-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "9100:443"
    links:
      - app-server
    volumes:
      - ./nginx/srv/dist/:/srv/dist/
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app-frontend:
    image: node:4.4.7-wheezy
    working_dir: /opt/raster-foundry/app-frontend/
    volumes:
      - ./app-frontend/.babelrc:/opt/raster-foundry/app-frontend/.babelrc
      - ./app-frontend/config/:/opt/raster-foundry/app-frontend/config/
      - ./nginx/srv/dist/:/opt/raster-foundry/app-frontend/dist/
      - ./app-frontend/.eslintrc:/opt/raster-foundry/app-frontend/.eslintrc
      - ./app-frontend/karma.conf.js:/opt/raster-foundry/app-frontend/karma.conf.js
      - ./.node_modules:/opt/raster-foundry/app-frontend/node_modules
      - ./app-frontend/package.json:/opt/raster-foundry/app-frontend/package.json
      - ./app-frontend/src:/opt/raster-foundry/app-frontend/src
      - ./app-frontend/webpack.config.js:/opt/raster-foundry/app-frontend/webpack.config.js
    command: npm run build-watch

  app-server:
    image: quay.io/azavea/scala:2.11.8
    links:
      - postgres:database.raster-foundry.internal
    env_file: .env
    ports:
      - "9000:9000"
    volumes:
      - ./app-server/:/opt/raster-foundry/app-server/
      - ./.ivy2:/root/.ivy2
      - ./.sbt:/root/.sbt
    working_dir: /opt/raster-foundry/app-server/
    command: ./sbt app/run

  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    ports:
      - "8888:8080"

  swagger-ui:
    image: nginx:1.10.1-alpine
    volumes:
      - ./docs/swagger/:/usr/share/nginx/html:ro
    ports:
      - "9999:80"

  redis:
    image: redis:3-alpine

  airflow-webserver:
    image: raster-foundry-airflow
    volumes:
      - ./app-tasks/usr/local/airflow/:/usr/local/airflow/
      - ./app-tasks/dags/:/opt/raster-foundry/app-tasks/dags/
      - ./app-tasks/rf/:/opt/raster-foundry/app-tasks/rf/
      - ./app-tasks/rf/src/rf/:/usr/local/bin/rf/
      - $HOME/.aws:/root/.aws:ro
    build:
      context: ./app-tasks
      dockerfile: Dockerfile
    env_file: .env
    links:
      - postgres:database.raster-foundry.internal
      - redis:redis.raster-foundry.internal
    environment:
      - AIRFLOW_HOME=/usr/local/airflow
    ports:
      - "8080:8080"
    command: airflow webserver

  airflow-flower:
    image: raster-foundry-airflow
    volumes:
      - ./app-tasks/usr/local/airflow/:/usr/local/airflow/
    build:
      context: ./app-tasks
      dockerfile: Dockerfile
    links:
      - postgres:database.raster-foundry.internal
      - redis:redis.raster-foundry.internal
    env_file: .env
    environment:
      - AIRFLOW_HOME=/usr/local/airflow
    ports:
      - "5555:5555"
    command: airflow flower

  airflow-scheduler:
    image: raster-foundry-airflow
    volumes:
      - ./app-tasks/usr/local/airflow/:/usr/local/airflow/
      - ./app-tasks/dags/:/opt/raster-foundry/app-tasks/dags/
      - ./app-tasks/rf/:/opt/raster-foundry/app-tasks/rf/
      - ./app-tasks/rf/src/rf/:/usr/local/bin/rf/
      - $HOME/.aws:/root/.aws:ro
    build:
      context: ./app-tasks
      dockerfile: Dockerfile
    restart: always
    links:
      - postgres:database.raster-foundry.internal
      - redis:redis.raster-foundry.internal
    env_file: .env
    environment:
      - AIRFLOW_HOME=/usr/local/airflow
      - PYTHONPATH=/opt/raster-foundry/app-tasks/rf/src/
    command: airflow scheduler

  airflow-worker:
    image: raster-foundry-airflow
    volumes:
      - ./app-tasks/usr/local/airflow/:/usr/local/airflow/
      - ./app-tasks/dags/:/opt/raster-foundry/app-tasks/dags/
      - ./app-tasks/rf/:/opt/raster-foundry/app-tasks/rf/
      - ./app-tasks/rf/src/rf/:/usr/local/bin/rf/
      - $HOME/.aws:/root/.aws:ro
    build:
      context: ./app-tasks
      dockerfile: Dockerfile
    links:
      - postgres:database.raster-foundry.internal
      - redis:redis.raster-foundry.internal
      - app-server:rasterfoundry.com
    env_file: .env
    environment:
      - AIRFLOW_HOME=/usr/local/airflow
      - C_FORCE_ROOT=True
    command: airflow worker
